apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-demo-2-ingress
  namespace: nginx-demo-2
spec:
  rules:
  - host: nginx-demo-2.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-demo-2-service
            port:
              number: 80